#!/usr/bin/env bash
# Copy the two things this spike must test AS THEY ACTUALLY SHIP into ui/vendor/.
#
# Copies rather than symlinks or imports: the webview loads these over HTTP from ui/, and a
# symlink out of the served root is exactly what the static server's canonicalize-then-prefix
# check refuses. Copies rather than an npm dependency: both sources already live in this repo,
# and a spike that tests a DIFFERENT Dexie than the client ships answers the wrong question.
#
# ui/vendor is gitignored - it is a build product of this script, the same way node_modules is.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo="$(cd "$here/.." && pwd)"
vendor="$here/ui/vendor"

dexie_src="$repo/node/js/node_modules/dexie/dist/dexie.mjs"
ingest_src="$repo/video-ingest/src"

if [[ ! -f "$dexie_src" ]]; then
  echo "error: $dexie_src not found." >&2
  echo "       Run 'just install' in $repo/node first - this spike deliberately tests the" >&2
  echo "       same Dexie build the client ships, not a fresh one from npm." >&2
  exit 1
fi

if [[ ! -d "$ingest_src" ]]; then
  echo "error: $ingest_src not found (the video-ingest spike is the reference implementation" >&2
  echo "       whose lanes this spike re-runs inside a webview)." >&2
  exit 1
fi

rm -rf "$vendor"
mkdir -p "$vendor/video-ingest"

cp "$dexie_src" "$vendor/dexie.mjs"
# Flat copy: video-ingest's modules import each other relatively, so a flat directory is a
# working module graph with no build step.
cp "$ingest_src"/*.js "$vendor/video-ingest/"

dexie_version="$(node -e 'process.stdout.write(require("'"$repo"'/node/js/node_modules/dexie/package.json").version)' 2>/dev/null || echo unknown)"
ingest_head="$(cd "$repo" && git log -1 --format=%h -- video-ingest 2>/dev/null || echo unknown)"

cat > "$vendor/VENDORED.json" <<JSON
{
  "note": "Generated by sync-vendor.sh. Records WHAT was tested, so a result in README's table can be trusted later.",
  "dexie_version": "$dexie_version",
  "video_ingest_commit": "$ingest_head"
}
JSON

echo "vendored dexie $dexie_version and video-ingest ($ingest_head) into ui/vendor/"
